### ISSUE TITLE
Versionned binaries

### ISSUE THREAD

**Issue by bfontaine** [asm89/twig-lint#14]
Hi,

Would you mind providing versionned binaries? Something like this would be great:

```
https://asm89.github.io/d/twig-lint-1.0.1.phar
```

You can also put binaries in GitHub releases.

Versionned binaries don’t change and can be verified with a checksum. I’d like to write an [Homebrew](http://brew.sh/) formula for `twig-lint`, so people would be able to install your program with `brew install twig-lint`, but I need a versionned URL.

Thanks!

**Comment by asm89** [comment]
Yes, I'll tag + upload a new binary soon.

**Comment by asm89** [comment]
@bfontaine `brew install` would be pretty cool indeed. I think uploading to GH makes the most sense in that case.
