### ISSUE TITLE
Only print errors option

### ISSUE THREAD

**Issue by edhgoose** [asm89/twig-lint#17]
Hi,

It'd be awesome to be able to have an 'only errors' option for printing out. At the moment we lint all our files in our CI process and in the majority of cases we only want the errors to be shown.

In the meantime, I've used the following to filter output:

    twig-lint lint ./filepath | grep -v 'OK'

Thanks!

**Comment by asm89** [comment]
@edhgoose I'd be happy to take a PR for that. In theory your work around might exclude files with OK in the path.

How about we add a new option `--only-print-errors` to the `LintCommand`? Then use the value of that option to determine if we should print `OK` here: https://github.com/asm89/twig-lint/blob/50b1e427a3622d828d9612b2c2949bee32ce7981/src/Asm89/Twig/Lint/Command/LintCommand.php#L104.

We should probably add a summary add the end of the linting, so you can easily check if there were also a lot of OKs. I'll file a separate issue for it.
