### ISSUE TITLE
How do I allow Drupal 8 twig_tweak functions?

### ISSUE THREAD

**Issue by brooke-heaton** [asm89/twig-lint#41]
This package is part of Acquia's [BLT framework](https://github.com/acquia/blt), but it seems to fail when using the Drupal contributed module [twig_tweak](https://www.drupal.org/project/twig_tweak). How can I get twig-lint to recognize twig_tweak functions?

**Comment by Chi-teck** [comment]
I guess you need to specify those functions in BLT configuration.
https://github.com/acquia/blt/blob/9.1.0-alpha1/config/build.yml#L220

**Comment by asm89** [comment]
I guess the BLT framework should have more context on this.
