### ISSUE TITLE
Version `v1.0.2` reports itself as `v1.0.1`

### ISSUE THREAD

**Issue by krzysztof-sikorski** [asm89/twig-lint#44]
When I install `v1.0.2` via Composer the installed code claims to be `v1.0.1`:

```sh
$ twig-lint --version
Twig lint v1.0.1
```

I tried a few different variants of invoking Composer, but none of those installed a package that would report its version as `v1.0.2`:
- `composer global require "asm89/twig-lint" "@stable"`
- `composer global require "asm89/twig-lint" "1.0.2"`
- `composer global require --prefer-source "asm89/twig-lint" "1.0.2"`

**Comment by asm89** [comment]
Correct. It should be fixed for 1.0.3. https://github.com/asm89/twig-lint/commit/e5a829aa883f54f8ec50a68e441358809b4e7bbf
